
import { GoogleGenAI, Type } from "@google/genai";

export interface AIDetectionResult {
  probability: number;
  explanation: string;
}

/**
 * AI DETECTION SERVICE
 * Uses Gemini to analyze academic answers for AI patterns.
 */
class AIDetectionService {
  private ai: GoogleGenAI;

  constructor() {
    // Note: process.env.GEMINI_API_KEY is automatically handled in this environment
    this.ai = new GoogleGenAI({ apiKey: import.meta.env.VITE_GEMINI_API_KEY || '' });
  }

  async analyzeAnswer(text: string): Promise<AIDetectionResult> {
    try {
      const response = await this.ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: `Analyze the following text and estimate the probability that it was generated by an AI language model. Return:
        * AI probability percentage (0-100)
        * short explanation.
        Text: ${text}`,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              probability: {
                type: Type.NUMBER,
                description: "AI probability percentage (0-100)",
              },
              explanation: {
                type: Type.STRING,
                description: "Short reasoning for the probability score.",
              },
            },
            required: ["probability", "explanation"],
          },
        },
      });

      const result = JSON.parse(response.text || '{}');
      return {
        probability: result.probability ?? 0,
        explanation: result.explanation ?? "Analysis unavailable.",
      };
    } catch (error) {
      console.error("AI Detection Error:", error);
      return {
        probability: 0,
        explanation: "Failed to analyze content.",
      };
    }
  }
}

export const aiDetection = new AIDetectionService();
